= Pltap - lightweight unit testing framework for PL/SQL

Pltap is a lightweight libruary for PL/SQL unit testing.
It aims to be simple, easy to start and to have non-bloated
API.

== Install                                                             

=== Via sqlplus

Run:

----
@install.sql
----

=== Manual installation
	
First, run `pltap_ddl.sql`.
Then compile `pltap_ps.sql` and `pltap_pb.sql` files. That's all.


== Uninstall

In Sqlplus, run:

----
@uninstall.sql
----


== API

Testing is just a comparison of and expected value
against and actual one, and almost all testing
procedures just compares theirs parameters.

Tests' results may be printed via dbms_output(default option) or saved
in the `pltap_results` table.

Pltap uses https://testanything.org[TAP]-like format for reporting, which in general looks like this:

----
ok 1: Test case 1 description
ok 2: Test case 2 description
not ok 3: Test case 3 description
not ok 4: Test case 4 description
# Expected:123
# Got: 122
FAILED: 3,4
Failed 2/4 50% ok
0 hours 0 minutes 0.122 seconds
----

=== set_output_to_table()

Redirect output to the `pltap_results` table.

Generally, you want to call this procedure in the beginning of your
tests execution:

----
begin
    pltap.set_output_to_table();
    pltap.start_test();
    -- Test statements
    -- .....
    pltap.end_test();
end;
----

When ouput is redirected to the table, an optional description to
the `start_test` procedure may be passed. This description is saved in
the `description` column and is useful for distinguishing just runned tests
from the others(previous results, different test suites or probably
other user's tests).

How to get results from the table:

----
select description, output_text
from pltap_results
order by id;
----

or

----
select description, output_text
from pltap_results
where description = 'Test HR Module'
order by id;
----

Of course, you can clear the table before
testing:

----
begin
	-- Remove all data before testing.
    delete from pltap_results;

    pltap.set_output_to_table();
    pltap.start_test();
    -- Test statements
    -- .....
    pltap.end_test();
end;
----

Pltap uses autonomous transactions when prints
results to the table, so any rollback or exception
will not lead to results loss:

----
begin
	savepoint start_test;

	begin
		pltap.set_output_to_table();
		pltap.start_test('Test some module');

		-- insert test data
		insert into hr_statuses
		values(1, 'pending');

		-- Test statements
		-- ...

		pltap.end_test();
	exception
		when others then
			pltap.fail('Exception during testing');
	end;

	rollback to start_test;
end;
----

Despite the final rollback, all output will
be in the table.

=== set_output_to_screen()

Redirect output to the screen.

=== set_description(description)

Updates current description. Description is
used only when output is redirected to the `pltap_results` table.

Example:

----
begin
    pltap.set_output_to_table();

    pltap.start_test();

    pltap.set_description('Test numbers');

	pltap.eq(1, 2, '1 is equal to 2');
	pltap.eq(5, 5, '5 is equal to 5');

	pltap.set_description('Test strings');

	pltap.eq('one', 'two', 'One is equal to two');
	pltap.eq('five', 'five', 'Five is equal to five');

    pltap.end_test();
end;
----

If we get the results:

----
select description, output_text
from pltap_results a
order by a.id;
----

They will look like:

----
DESCRIPTION     OUTPUT_TEXT
Test numbers    not ok: 1 1 is equal to 2
Test numbers    # Expected:2
Test numbers    # Got: 1
Test numbers    ok 2 5 is equal to 5
Test strings    not ok: 3 One is equal to two
Test strings    # Expected: 'two'
Test strings    # Got: 'one'
Test strings    ok 4 Five is equal to five
Test strings    FAILED: 1,3
Test strings    Failed 2/4 50% ok
Test strings    0 hours 0 minutes 0.004 seconds
----

Note that report's summary isn't processed separately -
it has the same description that was set via last
`set_description` call.

=== start_test(description default null)

Prepares pltap's state for testing. Internally, this
procedure clears all buffer variables, resets
counters, remembers the start time.

Optional description will be used when output is redirected
to the `pltap_results` table. This code:

----
begin
    pltap.start_test('description');
    -- test statements
    -- ...
    pltap.end_test();
end;
----

is actually equal to this:

----
begin
    pltap.start_test();
    pltap.set_description('description');
    -- test statements
    -- ...
    pltap.end_test();
end;
----

=== start_test(tests_count, description default null)

Like `start_test(description)`, but prints tests count
in the report's header:

----
begin
    pltap.start_test(5);
    pltap.set_description('description');
    pltap.eq(1, 1, '1=1');
    pltap.end_test();
end;
----

Output:

----
1..5
ok 1 1=1
Failed 0/1 100% ok
0 hours 0 minutes 0.000 seconds
----

=== end_test()

Ends testing and printing report.

=== eq(got, want, description default null)

Compares got and want params. Success if they are
equal, fail otherwise. Prints additional info
when values are differ in the form like:

----
# Expected:4
# Got: 2
----

Note that diff isn't printed for blob types.

Supported types: Varchar2, Date, Number, Blob;

Example:

---



---






== Examples


=== Easy mode

----
    begin
        pltap.start_test;

        pltap.eq(2, 3, '2 = 3');
        pltap.eq('John Doe', 'NotJohnDoe',
             '"John Doe" is equal to "NotJohnDoe"');
        pltap.eq(to_date('1981.01.23', 'yyyy.mm.dd'),
	         to_date('1981.01.23', 'yyyy.mm.dd'),
		 'Dates are equal'
        );
        pltap.ok(Sysdate > sysdate -1, 'Today is later than yesterday');

        pltap.end_test;
    end;
----

This will produce output (via dbms_output.put_line):

----
not ok: 1 2 = 3
# Expected:3
# Got: 2
not ok: 2 "John Doe" is equal to "NotJohnDoe"
# Expected: 'NotJohnDoe'
# Got: 'John Doe'
ok 3 Dates are equal
ok 4 Today is later than yesterday
FAILED: 1,2
Failed 2/4 50% ok
0 hours 0 minutes ,001 seconds
----

=== Test a function

----
    declare
        /*
        || Return true for all non-zero
        || numbers.
        */
        function bool(
            val number
        ) return boolean
        is
        begin
            return (val <> 0);
        end;

    begin
        pltap.start_test;

        -- #bt-1: Pass non-zero number
        -- Expected result: Function return True
        pltap.ok(bool(1), 'bt-1: True for positive number');

        -- #bt-2: Pass negative number
	-- Expected result: True
	pltap.ok(bool(-20), 'bt-2: True for negative number');

        -- #bt-3: Pass zero
        -- Expected result: False
        -- Next 2 examples are the same
        pltap.ok(not bool(0), 'bt-3: False for zero');
        pltap.ok(bool(0) = False,  'bt-3: False for zero');

        -- #bt-4: Pass null
        -- Expected result: False.
        pltap.ok(bool(null) = False, 'False for null');

        pltap.end_test;
    end;
----

Result:

----
ok 1 bt-1: True for positive number
ok 2 bt-2: True for negative number
ok 3 bt-3: False for zero
ok 4 bt-3: False for zero
not ok: 5 False for null
FAILED: 5
Failed 1/5 80% ok
0 hours 0 minutes ,001 seconds
----

=== Test queries

To test query results, results_eq procedure is used. Queries can
be passed as sys_refcursors or strings.

----
declare
	cur_1_got sys_refcursor;
	cur_1_want sys_refcursor;

	query_2_got varchar2(1000);
	query_2_want varchar2(1000);
begin

	open cur_1_got for
	select 0.04, trunc(sysdate), 'Closed' from dual
	union
	select 1, trunc(sysdate) + 1, 'Open'  from dual
	union
	select 2, trunc(sysdate) + 2, 'Another string' from dual;

	open cur_1_want for
	select 0.04, trunc(sysdate), 'Closed' from dual
	union
	select 1, trunc(sysdate) + 1, 'Open'  from dual
	union
	select 2, trunc(sysdate) + 2, 'Another string' from dual;

	query_2_want := 'select sysdate + 1 from dual';
	query_2_got  := 'select sysdate - 1 from dual';

	pltap.start_test;

	pltap.results_eq(cur_1_got, cur_1_want, 'Cursors are equal');
	pltap.results_eq(query_2_got, query_2_want, 'Queries are equal');

	pltap.end_test;
end;
----

Results:

----
ok 1 Cursors are equal
not ok: 2 Queries are equal
FAILED: 2
Failed 1/2 50% ok
0 hours 0 minutes 0,002 seconds
----

== Save results to the table

For quick tests it's normal to "print" output via dbms_output
(This is what pltap does by default), but for large test
sets it's not a deal. In such cases we can save results in the pltap_results table:

----
begin
	pltap.start_test;

	pltap.set_output_to_table; -- 'Redirect' output to table

	pltap.ok(true, 'true is true');
	pltap.eq(2, 3, '2 = 3');
	pltap.eq('John', 'John', 'John is John');

	pltap.end_test;

end;
----

After that, we can see result:

----
select *
from pltap_results
order by id
----

== Run tests automatically

Pltap can execute your tests for you:

----
begin
	pltap.start_test;

	pltap.bulk_run('YOUR_CHEMA_USER', 'test_package');

	pltap.end_test;
end;
----

It will scan all packages owned by YOUR_SCHEMA_USER and execute stored procedures
named test_package.

